### PR TITLE
Bump version to 2.0.5

### PR DESCRIPTION
**Pull request by flavorjones**
I'd like to cut a point release:

- Support Nokogiri's new CPPFLAGS/LDFLAGS in v1.11 #163
- Gracefully handle future Nokogiri version that ships HTML5 support #171 
- Support Mageia using system libraries #165

### CODE REVIEW

**Review by stevecheckoway — APPROVED** [review]
LGTM.

Would you like me to push a new version?

**Comment by stevecheckoway** [comment]
A new gem, I meant.

**Comment by flavorjones** [comment]
If you're OK with pushing this version, I'm happy to do it.

**Comment by stevecheckoway** [comment]
Sounds good to me. Thanks!

**Pull request merged**
