### PR TITLE
Integrate gumbo

### PR DESCRIPTION
**Pull request by stevecheckoway**
This PR addresses https://github.com/rubys/nokogumbo/issues/52 by making a local copy of gumbo-parser in nokogumbo.

Additionally, it fixes two bugs in gumbo, only one of which we had a workaround (now deleted) in nokogumbo.

Fixing https://github.com/rubys/nokogumbo/issues/64 should now be doable.

### CODE REVIEW

**Comment by rubys** [comment]
Probably worth a major version number change?  2.0.0.

Also, [create a profile](https://rubygems.org/sign_up) on rubygems, and I will add you as an owner to this gem.

**Comment by stevecheckoway** [comment]
I suspect it's worth making a few other changes if we're going to go to 2.0. I'll write up some issues shortly so that I don't forget what I have in mind.

I created a [profile](https://rubygems.org/profiles/stevecheckoway) on rubygems.

**Comment by rubys** [comment]
> I created a profile on rubygems.

Added: https://rubygems.org/gems/nokogumbo/

I encourage you to add your name to gem.authors.

**Comment by craigbarnes** [comment]
@stevecheckoway you may find [this list](https://github.com/craigbarnes/lua-gumbo/tree/master/lib#libgumbo) useful.

**Pull request merged**
