### PR TITLE
Remove testing unsupported versions of Ruby

### PR DESCRIPTION
**Pull request by stevecheckoway**
Nokogiri requires Ruby version >= 2.1.0.

### CODE REVIEW

**Comment by rubys** [comment]
Why isn't the following sufficient?

https://github.com/rubys/nokogumbo/blob/master/Gemfile#L3

**Comment by stevecheckoway** [comment]
I'm not sure, but it doesn't appear to be. https://travis-ci.org/rubys/nokogumbo/builds/204781411

**Comment by rubys** [comment]
Weird.  Looks good now: https://travis-ci.org/rubys/nokogumbo/builds/219126923

**Comment by stevecheckoway** [comment]
Odd! Well, if it's not needed, it's not needed.

**Pull request closed without merging**
