### PR TITLE
Gentoo

### PR DESCRIPTION
**Pull request by svoop**
@rubys 

I've tested the hint by @MaximeD (see [this comment](/rubys/nokogumbo/issues/25#issuecomment-164453556) on my box and indeed, the Gentoo workaround is causing the gem not to build on Gentoo. This pull request therefore reverts both 1a8eb44b (mentioned workaround) and 19b25fe0 (non-working fix of 1.4.6 release).

My setup installes Rubies with `ruby-install` rather than Gentoo Ebuilds to prevent all kind of gotchas caused by the weird opinions Gentoo maintainers enforce (e.g. unbundling Rubygems). It is therefore possible that the now removed workaround from 1a8eb44b may break the Gentoo Ebuild of Nokogumbo. However, I don't see why it should since I've built against the Gentoo provided Gumbo lib. And even if it does, then the Gentoo Ebuild of Nokogumbo should add a patch to do the changes from 1a8eb44b. This is very common in Gentoo-land and much better than to add distribution specific hacks upstream.

Thanks for taking a look and for pushing a new release. (I've already updated the version in order to test it on my box.)

### CODE REVIEW

**Comment by svoop** [comment]
@rubys By the way, once the Gentoo workaround is removed, I can open a bug on Gentoo to document the change and as a heads up in case the Nokogumbo ebuild needs a patch afterwards. Since the patch can just be taken from 1a8eb44, this should not cause any trouble.

**Comment by rubys** [comment]
gem pushed: https://rubygems.org/gems/nokogumbo/versions/1.4.7

**Comment by svoop** [comment]
Big thanks @rubys, works like a charm now on my box. I've created the heads-up upstream:
https://bugs.gentoo.org/show_bug.cgi?id=568668

**Comment by svoop** [comment]
The maintainer on Gentoo has just extended the Nokogumbu ebuild to properly link without this workaround present, so everybody's happy now :smile:

**Pull request merged**
